// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgOcdkKVLlSve-dxykZ_3Rbot_ZkUiBak',
    appId: '1:138616472149:web:9cf0c1132a6964df378adc',
    messagingSenderId: '138616472149',
    projectId: 'kiosk-finder-d281b',
    authDomain: 'kiosk-finder-d281b.firebaseapp.com',
    storageBucket: 'kiosk-finder-d281b.firebasestorage.app',
    measurementId: 'G-QTYZQ8NS4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE6x_bsy3GlGKW4iCNOXeIHhGK2xfbjHI',
    appId: '1:138616472149:android:568d9936ec0dcd47378adc',
    messagingSenderId: '138616472149',
    projectId: 'kiosk-finder-d281b',
    storageBucket: 'kiosk-finder-d281b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-x43uxYKvF0TimDjNyzq2abftGVh52yE',
    appId: '1:138616472149:ios:81c1d93004427daf378adc',
    messagingSenderId: '138616472149',
    projectId: 'kiosk-finder-d281b',
    storageBucket: 'kiosk-finder-d281b.firebasestorage.app',
    iosBundleId: 'com.example.kioskFinder',
  );
}
